Fix Bug
Fixed the backpropogation calculation in the MCTS.train_function by
changing the player-wise updates of the visited_nodes.
The code now mostly works as expected. A new issue is that the line which
obtains the optimal node/move sometimes throws the exception,
ValueError: max() arg is an empty sequence.